### PR TITLE
Implementation sync.Cond Demo without time.Sleep

### PR DESCRIPTION
**Pull request by hhh111119**
Hi thanks for your project which is brilliant.
I just found the demo for sync.Cond which use time.Sleep(time.Second).  
It's looks a little tricky here for me. I just proposal a new implementation for this demo.
I haven't push the test code and just paste here.
the command I used is 
go test -race  main.go  main_test.go -v
```go
package main

import "testing"

func Test_listing4(t *testing.T) {
	tests := []struct {
		name string
	}{
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			listing4()
		})
	}
}
```
Hope it can helps. :)

### CODE REVIEW

**Comment by teivah** [comment]
What is the issue with having a call to `time.Sleep` in the example? (given the fact that it's used to simulate a client updating the balance every second)

**Comment by hhh111119** [comment]
Hi, my thought is
first time.Sleep, make the goroutine sleep one second but it seem can't strong guarantee other two goroutine get the cond.Lock before the the main goroutine waked and locked again.  There is no happens before here. But sure it's may never happen in reality. 

second,  if it's simulate a real business, it may not need to switch the goroutine and wait one second. so if this program running on one core machine, the balance could be over the goal when detected by other two goroutine.

**Comment by teivah** [comment]
Sorry, I'm not sure to understand clearly what you mean by "but it seem can't strong guarantee".

If you refer to the fact that when there's no active receiver, the notification will be missed, then it's covered in the book. I highlight it as a drawback.

**Comment by hhh111119** [comment]
> the notification will be missed
oh yes this is what I mean.

**Comment by teivah** [comment]
The goal was to build a simple example so that people understand how to use sync.Cond. Thanks for your PR, but I'm not going to merge it.

**Pull request closed without merging**
